# Generated by Django 2.0 on 2018-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
